import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  Contact,
  FileText,
  FolderKanban,
  GalleryHorizontalEnd,
  Globe2,
  Home,
  Image,
  LayoutDashboard,
  Mail,
  MapPinned,
  Megaphone,
  MessageSquare,
  Newspaper,
  PanelsTopLeft,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Star,
  Users,
  Wrench,
} from "lucide-react";
import { COLLECTIONS, type CollectionId } from "@/constants/collections";
import { ROUTES } from "@/constants/routes";

export type AdminFieldType =
  | "text"
  | "textarea"
  | "richtext"
  | "number"
  | "currency"
  | "email"
  | "url"
  | "date"
  | "datetime"
  | "select"
  | "multiselect"
  | "boolean"
  | "tags"
  | "image"
  | "file"
  | "json";

export interface AdminField {
  name: string;
  label: string;
  type: AdminFieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  section?: string;
  min?: number;
  max?: number;
}

export interface AdminModuleConfig {
  id: string;
  title: string;
  singular: string;
  description: string;
  route: string;
  collectionId: CollectionId;
  icon: LucideIcon;
  group: "Dashboard" | "CMS" | "Commerce" | "People" | "Inbox" | "System";
  searchFields: string[];
  primaryField: string;
  statusField?: string;
  readOnly?: boolean;
  fields: AdminField[];
  tableColumns: string[];
}

const statusOptions = ["draft", "published", "archived"];
const requestStatusOptions = ["new", "in-review", "replied", "closed", "archived"];

const commonCmsFields: AdminField[] = [
  { name: "slug", label: "Slug", type: "text", required: true, section: "Publishing" },
  { name: "status", label: "Status", type: "select", options: statusOptions, required: true, section: "Publishing" },
  { name: "sortOrder", label: "Sort Order", type: "number", section: "Publishing" },
  { name: "featured", label: "Featured", type: "boolean", section: "Publishing" },
  { name: "seoTitle", label: "SEO Title", type: "text", section: "SEO" },
  { name: "seoDescription", label: "SEO Description", type: "textarea", section: "SEO" },
  { name: "seoKeywords", label: "SEO Keywords", type: "tags", section: "SEO" },
];

function cms(fields: AdminField[]): AdminField[] {
  return [...fields, ...commonCmsFields];
}

export const adminModules: AdminModuleConfig[] = [
  {
    id: "homepage",
    title: "Homepage",
    singular: "Homepage Section",
    description: "Hero, statistics, banners, CTAs, and homepage content blocks.",
    route: ROUTES.ADMIN_HOMEPAGE,
    collectionId: COLLECTIONS.HOMEPAGE,
    icon: Home,
    group: "CMS",
    searchFields: ["title", "subtitle", "section"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "section", "status", "sortOrder", "$updatedAt"],
    fields: cms([
      { name: "section", label: "Section", type: "select", required: true, options: ["hero", "statistics", "banner", "cta", "feature", "content"] },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "description", label: "Description", type: "richtext" },
      { name: "buttonLabel", label: "Button Label", type: "text" },
      { name: "buttonUrl", label: "Button URL", type: "url" },
      { name: "backgroundMediaId", label: "Background", type: "image" },
      { name: "heroImageId", label: "Hero Image", type: "image" },
      { name: "statistics", label: "Statistics JSON", type: "json" },
    ]),
  },
  {
    id: "about",
    title: "About Us",
    singular: "About Content",
    description: "Company story, vision, mission, CEO message, timeline, and achievements.",
    route: ROUTES.ADMIN_ABOUT,
    collectionId: COLLECTIONS.ABOUT,
    icon: Building2,
    group: "CMS",
    searchFields: ["title", "section"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "section", "status", "sortOrder", "$updatedAt"],
    fields: cms([
      { name: "section", label: "Section", type: "select", required: true, options: ["story", "vision", "mission", "ceo-message", "timeline", "certificate", "achievement"] },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "content", label: "Content", type: "richtext" },
      { name: "mediaId", label: "Image or Certificate", type: "image" },
      { name: "year", label: "Year", type: "number" },
      { name: "linkUrl", label: "Link URL", type: "url" },
    ]),
  },
  {
    id: "services",
    title: "Services",
    singular: "Service",
    description: "Service catalog, categories, pricing references, features, imagery, and ordering.",
    route: ROUTES.ADMIN_SERVICES,
    collectionId: COLLECTIONS.SERVICES,
    icon: Wrench,
    group: "CMS",
    searchFields: ["name", "category", "shortDescription"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "category", "status", "featured", "$updatedAt"],
    fields: cms([
      { name: "name", label: "Service Name", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "shortDescription", label: "Short Description", type: "textarea", required: true },
      { name: "description", label: "Description", type: "richtext", required: true },
      { name: "features", label: "Features", type: "tags" },
      { name: "pricing", label: "Pricing", type: "text" },
      { name: "imageMediaId", label: "Image", type: "image" },
      { name: "iconMediaId", label: "Icon", type: "image" },
    ]),
  },
  {
    id: "projects",
    title: "Projects",
    singular: "Project",
    description: "Project case studies with galleries, technologies, client, location, timeline, and status.",
    route: ROUTES.ADMIN_PROJECTS,
    collectionId: COLLECTIONS.PROJECTS,
    icon: FolderKanban,
    group: "CMS",
    searchFields: ["title", "summary", "clientName", "location"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "clientName", "location", "status", "featured", "$updatedAt"],
    fields: cms([
      { name: "title", label: "Project Title", type: "text", required: true },
      { name: "summary", label: "Summary", type: "textarea", required: true },
      { name: "description", label: "Description", type: "richtext" },
      { name: "clientName", label: "Client", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "technologies", label: "Technologies", type: "tags" },
      { name: "timeline", label: "Timeline", type: "text" },
      { name: "galleryMediaIds", label: "Gallery IDs", type: "tags" },
      { name: "coverImageId", label: "Cover Image", type: "image" },
      { name: "liveUrl", label: "Live URL", type: "url" },
    ]),
  },
  {
    id: "solutions",
    title: "Solutions",
    singular: "Solution",
    description: "Business solution pages grouped by industry, service area, and customer need.",
    route: ROUTES.ADMIN_SOLUTIONS,
    collectionId: COLLECTIONS.SOLUTIONS,
    icon: LayoutDashboard,
    group: "CMS",
    searchFields: ["name", "description", "category"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "category", "status", "featured", "$updatedAt"],
    fields: cms([
      { name: "name", label: "Solution Name", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "richtext", required: true },
      { name: "industryIds", label: "Industry IDs", type: "tags" },
      { name: "serviceIds", label: "Service IDs", type: "tags" },
      { name: "imageMediaId", label: "Image", type: "image" },
    ]),
  },
  {
    id: "industries",
    title: "Industries",
    singular: "Industry",
    description: "Industry pages, icons, descriptions, featured order, and SEO metadata.",
    route: ROUTES.ADMIN_INDUSTRIES,
    collectionId: COLLECTIONS.INDUSTRIES,
    icon: Building2,
    group: "CMS",
    searchFields: ["name", "description"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "status", "featured", "sortOrder", "$updatedAt"],
    fields: cms([
      { name: "name", label: "Industry Name", type: "text", required: true },
      { name: "description", label: "Description", type: "richtext" },
      { name: "iconMediaId", label: "Icon", type: "image" },
      { name: "imageMediaId", label: "Image", type: "image" },
    ]),
  },
  {
    id: "technologies",
    title: "Technologies",
    singular: "Technology",
    description: "Technology stack entries, categories, icons, featured state, and ordering.",
    route: ROUTES.ADMIN_TECHNOLOGIES,
    collectionId: COLLECTIONS.TECHNOLOGIES,
    icon: Globe2,
    group: "CMS",
    searchFields: ["name", "category"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "category", "status", "featured", "$updatedAt"],
    fields: cms([
      { name: "name", label: "Technology Name", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "iconMediaId", label: "Icon", type: "image" },
      { name: "description", label: "Description", type: "textarea" },
    ]),
  },
  {
    id: "products",
    title: "Products",
    singular: "Product",
    description: "Products, specifications, downloads, pricing, inventory, and product media.",
    route: ROUTES.ADMIN_PRODUCTS,
    collectionId: COLLECTIONS.PRODUCTS,
    icon: ShoppingBag,
    group: "Commerce",
    searchFields: ["name", "sku", "category"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "sku", "category", "price", "inventory", "status"],
    fields: cms([
      { name: "name", label: "Product Name", type: "text", required: true },
      { name: "sku", label: "SKU", type: "text" },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "richtext" },
      { name: "specifications", label: "Specifications JSON", type: "json" },
      { name: "downloadMediaIds", label: "Download File IDs", type: "tags" },
      { name: "imageMediaIds", label: "Image IDs", type: "tags" },
      { name: "price", label: "Price", type: "currency" },
      { name: "inventory", label: "Inventory", type: "number" },
    ]),
  },
  {
    id: "portfolio",
    title: "Portfolio",
    singular: "Portfolio Item",
    description: "Portfolio entries with galleries, videos, categories, and tags.",
    route: ROUTES.ADMIN_PORTFOLIO,
    collectionId: COLLECTIONS.PORTFOLIO,
    icon: PanelsTopLeft,
    group: "CMS",
    searchFields: ["title", "category", "tags"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "category", "status", "featured", "$updatedAt"],
    fields: cms([
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "richtext" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "galleryMediaIds", label: "Gallery IDs", type: "tags" },
      { name: "videoMediaIds", label: "Video IDs", type: "tags" },
      { name: "coverImageId", label: "Cover Image", type: "image" },
    ]),
  },
  {
    id: "team",
    title: "Team Members",
    singular: "Team Member",
    description: "People profiles, designations, social links, experience, bios, and photos.",
    route: ROUTES.ADMIN_TEAM,
    collectionId: COLLECTIONS.TEAM_MEMBERS,
    icon: Users,
    group: "People",
    searchFields: ["name", "designation", "department"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "designation", "department", "status", "$updatedAt"],
    fields: cms([
      { name: "name", label: "Name", type: "text", required: true },
      { name: "designation", label: "Designation", type: "text", required: true },
      { name: "department", label: "Department", type: "text" },
      { name: "experienceYears", label: "Experience Years", type: "number" },
      { name: "bio", label: "Bio", type: "richtext" },
      { name: "photoMediaId", label: "Photo", type: "image" },
      { name: "socialLinks", label: "Social Links JSON", type: "json" },
    ]),
  },
  {
    id: "careers",
    title: "Careers",
    singular: "Job Post",
    description: "Job posts, departments, skills, salary, location, experience, and employment type.",
    route: ROUTES.ADMIN_CAREERS,
    collectionId: COLLECTIONS.JOBS,
    icon: BriefcaseBusiness,
    group: "People",
    searchFields: ["title", "department", "location"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "department", "location", "employmentType", "status"],
    fields: cms([
      { name: "title", label: "Job Title", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "skills", label: "Skills", type: "tags" },
      { name: "salaryRange", label: "Salary Range", type: "text" },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "experience", label: "Experience", type: "text" },
      { name: "employmentType", label: "Employment Type", type: "select", required: true, options: ["full-time", "part-time", "contract", "internship"] },
      { name: "description", label: "Description", type: "richtext", required: true },
    ]),
  },
  {
    id: "applications",
    title: "Applications",
    singular: "Application",
    description: "Job applications with resume references, review status, and candidate details.",
    route: ROUTES.ADMIN_APPLICATIONS,
    collectionId: COLLECTIONS.APPLICATIONS,
    icon: FileText,
    group: "Inbox",
    searchFields: ["applicantName", "applicantEmail", "jobTitle"],
    primaryField: "applicantName",
    statusField: "status",
    tableColumns: ["applicantName", "applicantEmail", "jobTitle", "status", "$createdAt"],
    fields: [
      { name: "jobId", label: "Job ID", type: "text", required: true },
      { name: "jobTitle", label: "Job Title", type: "text" },
      { name: "applicantName", label: "Applicant Name", type: "text", required: true },
      { name: "applicantEmail", label: "Applicant Email", type: "email", required: true },
      { name: "applicantPhone", label: "Applicant Phone", type: "text" },
      { name: "resumeMediaId", label: "Resume File", type: "file" },
      { name: "coverNote", label: "Cover Note", type: "textarea" },
      { name: "status", label: "Status", type: "select", required: true, options: ["new", "shortlisted", "interview", "rejected", "hired"] },
    ],
  },
  {
    id: "blogs",
    title: "Blog",
    singular: "Blog Post",
    description: "Rich articles, categories, tags, author, thumbnail, SEO, and publishing schedule.",
    route: ROUTES.ADMIN_BLOGS,
    collectionId: COLLECTIONS.BLOGS,
    icon: Newspaper,
    group: "CMS",
    searchFields: ["title", "category", "author"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "category", "author", "status", "publishDate"],
    fields: cms([
      { name: "title", label: "Title", type: "text", required: true },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "content", label: "Content", type: "richtext", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "tags", label: "Tags", type: "tags" },
      { name: "author", label: "Author", type: "text" },
      { name: "thumbnailMediaId", label: "Thumbnail", type: "image" },
      { name: "publishDate", label: "Publish Date", type: "date" },
    ]),
  },
  {
    id: "testimonials",
    title: "Testimonials",
    singular: "Testimonial",
    description: "Testimonials, ratings, photos, company names, and approval state.",
    route: ROUTES.ADMIN_TESTIMONIALS,
    collectionId: COLLECTIONS.TESTIMONIALS,
    icon: Star,
    group: "CMS",
    searchFields: ["clientName", "clientCompany", "quote"],
    primaryField: "clientName",
    statusField: "status",
    tableColumns: ["clientName", "clientCompany", "rating", "status", "$updatedAt"],
    fields: cms([
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "clientCompany", label: "Company", type: "text" },
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "rating", label: "Rating", type: "number", required: true, min: 1, max: 5 },
      { name: "avatarMediaId", label: "Photo", type: "image" },
      { name: "videoMediaId", label: "Video", type: "file" },
    ]),
  },
  {
    id: "clients",
    title: "Clients",
    singular: "Client",
    description: "Client logos, website links, descriptions, and publishing state.",
    route: ROUTES.ADMIN_CLIENTS,
    collectionId: COLLECTIONS.CLIENTS,
    icon: Building2,
    group: "People",
    searchFields: ["name", "websiteUrl", "description"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "websiteUrl", "status", "featured", "$updatedAt"],
    fields: cms([
      { name: "name", label: "Client Name", type: "text", required: true },
      { name: "logoMediaId", label: "Logo", type: "image" },
      { name: "websiteUrl", label: "Website", type: "url" },
      { name: "description", label: "Description", type: "textarea" },
    ]),
  },
  {
    id: "gallery",
    title: "Gallery",
    singular: "Gallery Item",
    description: "Images, videos, albums, categories, captions, and display ordering.",
    route: ROUTES.ADMIN_GALLERY,
    collectionId: COLLECTIONS.GALLERY,
    icon: GalleryHorizontalEnd,
    group: "CMS",
    searchFields: ["title", "album", "category"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "type", "album", "category", "status"],
    fields: cms([
      { name: "title", label: "Title", type: "text", required: true },
      { name: "type", label: "Type", type: "select", required: true, options: ["image", "video"] },
      { name: "mediaId", label: "Media", type: "image" },
      { name: "album", label: "Album", type: "text" },
      { name: "category", label: "Category", type: "text" },
      { name: "caption", label: "Caption", type: "textarea" },
    ]),
  },
  {
    id: "contact",
    title: "Contact Requests",
    singular: "Contact Request",
    description: "Inbound contact messages with search, filters, reply notes, delete, and export.",
    route: ROUTES.ADMIN_CONTACT,
    collectionId: COLLECTIONS.CONTACT_REQUESTS,
    icon: Contact,
    group: "Inbox",
    searchFields: ["name", "email", "subject", "message"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "email", "subject", "status", "$createdAt"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "replyNote", label: "Reply Note", type: "textarea" },
      { name: "status", label: "Status", type: "select", required: true, options: requestStatusOptions },
    ],
  },
  {
    id: "newsletter",
    title: "Newsletter",
    singular: "Subscriber",
    description: "Newsletter subscriber management with CSV export and suppression state.",
    route: ROUTES.ADMIN_NEWSLETTER,
    collectionId: COLLECTIONS.NEWSLETTER,
    icon: Mail,
    group: "Inbox",
    searchFields: ["email", "name"],
    primaryField: "email",
    statusField: "status",
    tableColumns: ["email", "name", "source", "status", "$createdAt"],
    fields: [
      { name: "email", label: "Email", type: "email", required: true },
      { name: "name", label: "Name", type: "text" },
      { name: "source", label: "Source", type: "text" },
      { name: "status", label: "Status", type: "select", required: true, options: ["subscribed", "unsubscribed", "bounced"] },
    ],
  },
  {
    id: "faq",
    title: "FAQ",
    singular: "FAQ",
    description: "Frequently asked questions with categories and sort order.",
    route: ROUTES.ADMIN_FAQ,
    collectionId: COLLECTIONS.FAQS,
    icon: MessageSquare,
    group: "CMS",
    searchFields: ["question", "answer", "category"],
    primaryField: "question",
    statusField: "status",
    tableColumns: ["question", "category", "sortOrder", "status", "$updatedAt"],
    fields: cms([
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Answer", type: "richtext", required: true },
      { name: "category", label: "Category", type: "text" },
    ]),
  },
  {
    id: "policies",
    title: "Policies",
    singular: "Policy",
    description: "Privacy policy, terms, refund, shipping, cookies, and other legal pages.",
    route: ROUTES.ADMIN_POLICIES,
    collectionId: COLLECTIONS.POLICIES,
    icon: ShieldCheck,
    group: "System",
    searchFields: ["title", "type"],
    primaryField: "title",
    statusField: "status",
    tableColumns: ["title", "type", "status", "$updatedAt"],
    fields: cms([
      { name: "type", label: "Policy Type", type: "select", required: true, options: ["privacy", "terms", "refund", "shipping", "cookies"] },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "content", label: "Content", type: "richtext", required: true },
      { name: "effectiveDate", label: "Effective Date", type: "date" },
    ]),
  },
  {
    id: "settings",
    title: "Website Settings",
    singular: "Setting",
    description: "Company identity, logo, favicon, contacts, map, social links, SEO, analytics, and footer.",
    route: ROUTES.ADMIN_SETTINGS,
    collectionId: COLLECTIONS.SETTINGS,
    icon: Settings,
    group: "System",
    searchFields: ["key", "group", "value"],
    primaryField: "key",
    tableColumns: ["key", "group", "value", "$updatedAt"],
    fields: [
      { name: "group", label: "Group", type: "select", required: true, options: ["company", "brand", "contact", "map", "social", "seo", "analytics", "footer", "smtp", "backup", "maintenance"] },
      { name: "key", label: "Key", type: "text", required: true },
      { name: "value", label: "Value", type: "json", required: true },
    ],
  },
  {
    id: "menus",
    title: "Menus",
    singular: "Menu Item",
    description: "Header, footer, and sidebar navigation with drag-sort compatible order fields.",
    route: ROUTES.ADMIN_MENUS,
    collectionId: COLLECTIONS.MENUS,
    icon: MapPinned,
    group: "System",
    searchFields: ["label", "path", "menu"],
    primaryField: "label",
    statusField: "status",
    tableColumns: ["label", "menu", "path", "sortOrder", "status"],
    fields: [
      { name: "menu", label: "Menu", type: "select", required: true, options: ["header", "footer", "sidebar"] },
      { name: "label", label: "Label", type: "text", required: true },
      { name: "path", label: "Path", type: "text", required: true },
      { name: "parentId", label: "Parent ID", type: "text" },
      { name: "sortOrder", label: "Sort Order", type: "number" },
      { name: "status", label: "Status", type: "select", required: true, options: statusOptions },
    ],
  },
  {
    id: "media",
    title: "Media Library",
    singular: "Media Asset",
    description: "Image, video, and PDF uploads with folders, search, preview, and delete.",
    route: ROUTES.ADMIN_MEDIA,
    collectionId: COLLECTIONS.MEDIA,
    icon: Image,
    group: "System",
    searchFields: ["fileName", "folder", "altText"],
    primaryField: "fileName",
    tableColumns: ["fileName", "fileType", "folder", "altText", "$createdAt"],
    fields: [
      { name: "fileId", label: "Storage File ID", type: "file", required: true },
      { name: "fileName", label: "File Name", type: "text", required: true },
      { name: "fileType", label: "File Type", type: "select", required: true, options: ["image", "video", "pdf", "document", "other"] },
      { name: "folder", label: "Folder", type: "text" },
      { name: "altText", label: "Alt Text", type: "text" },
    ],
  },
  {
    id: "users",
    title: "User Management",
    singular: "Admin User",
    description: "Admin, editor, manager, and staff users with roles and permissions.",
    route: ROUTES.ADMIN_USERS,
    collectionId: COLLECTIONS.USERS,
    icon: Users,
    group: "System",
    searchFields: ["name", "email", "role"],
    primaryField: "name",
    statusField: "status",
    tableColumns: ["name", "email", "role", "status", "$updatedAt"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "role", label: "Role", type: "select", required: true, options: ["admin", "editor", "manager", "staff"] },
      { name: "permissions", label: "Permissions", type: "tags" },
      { name: "status", label: "Status", type: "select", required: true, options: ["active", "suspended", "invited"] },
    ],
  },
  {
    id: "quotes",
    title: "Enquiries",
    singular: "Quote Request",
    description: "Quote requests, budgets, timelines, requirements, attachments, and response status.",
    route: ROUTES.ADMIN_QUOTES,
    collectionId: COLLECTIONS.QUOTES,
    icon: Megaphone,
    group: "Inbox",
    searchFields: ["contactName", "contactEmail", "projectType", "requirements"],
    primaryField: "contactName",
    statusField: "status",
    tableColumns: ["contactName", "projectType", "budgetRange", "status", "$createdAt"],
    fields: [
      { name: "projectType", label: "Project Type", type: "text", required: true },
      { name: "budgetRange", label: "Budget Range", type: "text", required: true },
      { name: "timeline", label: "Timeline", type: "text", required: true },
      { name: "requirements", label: "Requirements", type: "textarea", required: true },
      { name: "contactName", label: "Contact Name", type: "text", required: true },
      { name: "contactEmail", label: "Contact Email", type: "email", required: true },
      { name: "contactPhone", label: "Contact Phone", type: "text" },
      { name: "status", label: "Status", type: "select", required: true, options: requestStatusOptions },
    ],
  },
  {
    id: "appointments",
    title: "Appointments",
    singular: "Appointment",
    description: "Consultation appointments, meeting type, schedule, duration, links, and notes.",
    route: ROUTES.ADMIN_APPOINTMENTS,
    collectionId: COLLECTIONS.APPOINTMENTS,
    icon: CalendarCheck,
    group: "Inbox",
    searchFields: ["contactName", "contactEmail", "meetingType"],
    primaryField: "contactName",
    statusField: "status",
    tableColumns: ["contactName", "meetingType", "scheduledAt", "status", "$createdAt"],
    fields: [
      { name: "contactName", label: "Contact Name", type: "text", required: true },
      { name: "contactEmail", label: "Contact Email", type: "email", required: true },
      { name: "meetingType", label: "Meeting Type", type: "select", required: true, options: ["video", "phone", "in-person"] },
      { name: "scheduledAt", label: "Scheduled At", type: "datetime", required: true },
      { name: "durationMinutes", label: "Duration Minutes", type: "number", required: true },
      { name: "googleMeetLink", label: "Meeting Link", type: "url" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "status", label: "Status", type: "select", required: true, options: ["pending", "confirmed", "completed", "cancelled"] },
    ],
  },
  {
    id: "analytics",
    title: "Analytics",
    singular: "Analytics Event",
    description: "Visitor, lead, project, application, and traffic events.",
    route: ROUTES.ADMIN_ANALYTICS,
    collectionId: COLLECTIONS.ANALYTICS,
    icon: BarChart3,
    group: "Dashboard",
    searchFields: ["eventType", "path"],
    primaryField: "eventType",
    tableColumns: ["eventType", "path", "occurredAt", "$createdAt"],
    fields: [
      { name: "eventType", label: "Event Type", type: "text", required: true },
      { name: "path", label: "Path", type: "text" },
      { name: "metadata", label: "Metadata JSON", type: "json" },
      { name: "occurredAt", label: "Occurred At", type: "datetime", required: true },
    ],
  },
  {
    id: "audit",
    title: "Audit Logs",
    singular: "Audit Log",
    description: "Activity logs, admin logs, login history, and change history.",
    route: ROUTES.ADMIN_AUDIT,
    collectionId: COLLECTIONS.AUDIT_LOGS,
    icon: Activity,
    group: "System",
    searchFields: ["actorName", "action", "entityType", "entityId"],
    primaryField: "action",
    tableColumns: ["actorName", "action", "entityType", "entityId", "$createdAt"],
    readOnly: true,
    fields: [
      { name: "actorName", label: "Actor", type: "text", required: true },
      { name: "actorEmail", label: "Actor Email", type: "email" },
      { name: "action", label: "Action", type: "text", required: true },
      { name: "entityType", label: "Entity Type", type: "text" },
      { name: "entityId", label: "Entity ID", type: "text" },
      { name: "changes", label: "Changes JSON", type: "json" },
    ],
  },
  {
    id: "seo",
    title: "SEO & Meta",
    singular: "SEO Entry",
    description: "Page-level metadata, analytics snippets, canonical URLs, and Open Graph media.",
    route: ROUTES.ADMIN_SEO,
    collectionId: COLLECTIONS.SEO,
    icon: Globe2,
    group: "System",
    searchFields: ["page", "title", "description"],
    primaryField: "page",
    tableColumns: ["page", "title", "canonicalUrl", "$updatedAt"],
    fields: [
      { name: "page", label: "Page", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "keywords", label: "Keywords", type: "tags" },
      { name: "canonicalUrl", label: "Canonical URL", type: "url" },
      { name: "ogImageMediaId", label: "Open Graph Image", type: "image" },
      { name: "robots", label: "Robots", type: "text" },
    ],
  },
];

export const adminModulesByRoute = new Map(adminModules.map((module) => [module.route, module]));
export const adminModulesById = new Map(adminModules.map((module) => [module.id, module]));

export const dashboardCards = [
  { label: "Total Companies", collectionId: COLLECTIONS.COMPANY, icon: Building2 },
  { label: "Total Services", collectionId: COLLECTIONS.SERVICES, icon: Wrench },
  { label: "Total Projects", collectionId: COLLECTIONS.PROJECTS, icon: FolderKanban },
  { label: "Total Clients", collectionId: COLLECTIONS.CLIENTS, icon: Building2 },
  { label: "Total Employees", collectionId: COLLECTIONS.TEAM_MEMBERS, icon: Users },
  { label: "Total Job Posts", collectionId: COLLECTIONS.JOBS, icon: BriefcaseBusiness },
  { label: "Total Applications", collectionId: COLLECTIONS.APPLICATIONS, icon: FileText },
  { label: "Total Gallery Images", collectionId: COLLECTIONS.GALLERY, icon: GalleryHorizontalEnd },
  { label: "Total Blogs", collectionId: COLLECTIONS.BLOGS, icon: Newspaper },
  { label: "Total Testimonials", collectionId: COLLECTIONS.TESTIMONIALS, icon: Star },
  { label: "Total Contacts", collectionId: COLLECTIONS.CONTACT_REQUESTS, icon: Contact },
  { label: "Total Enquiries", collectionId: COLLECTIONS.QUOTES, icon: Megaphone },
];

export const quickActionModuleIds = [
  "homepage",
  "services",
  "projects",
  "blogs",
  "media",
  "settings",
];
