import { COLLECTIONS } from "@/constants/collections";
import { ROUTES } from "@/constants/routes";
import type { PublicPageConfig } from "@/components/public/CmsPage";

export const publicPageConfigs = {
  home: {
    eyebrow: "Enterprise software partner",
    title: "Build the systems your company can confidently run on",
    subtitle:
      "We design websites, applications, automation workflows, and AI-enabled platforms for teams that need reliable software and measurable business outcomes.",
    collectionId: COLLECTIONS.HOME,
    searchFields: ["title", "subtitle", "description"],
    primaryField: "title",
    descriptionField: "description",
    imageField: "heroImageId",
    categoryField: "section",
    ctaLabel: "Get a quote",
    ctaPath: ROUTES.QUOTE,
    variant: "home",
    fallback: [
      {
        $id: "home-hero",
        title: "Enterprise websites, apps, and automation built for growth",
        description:
          "DAN Enterprise helps companies modernize their digital presence, streamline operations, and launch software that is fast, elegant, secure, and easy to manage from the admin portal.",
        section: "hero",
      },
      {
        $id: "home-services",
        title: "Digital products engineered end to end",
        description: "From strategy and UI to Appwrite-backed CMS workflows, every layer is planned for maintainability.",
        section: "feature",
      },
      {
        $id: "home-automation",
        title: "Operational automation",
        description: "Lead capture, careers, content, analytics, and admin processes are designed as connected workflows.",
        section: "feature",
      },
      {
        $id: "home-support",
        title: "Built for ownership",
        description: "Your team can update content, media, settings, menus, and enquiries without editing source code.",
        section: "feature",
      },
    ],
  },
  about: {
    eyebrow: "About us",
    title: "A software company focused on clarity, reliability, and momentum",
    subtitle:
      "We partner with growing companies to turn digital ideas into dependable systems, combining thoughtful design with disciplined engineering.",
    collectionId: COLLECTIONS.ABOUT,
    searchFields: ["title", "content", "section"],
    primaryField: "title",
    descriptionField: "content",
    imageField: "mediaId",
    categoryField: "section",
    ctaLabel: "Talk to us",
    ctaPath: ROUTES.CONTACT,
    variant: "about",
    fallback: [
      {
        $id: "about-story",
        title: "Company story",
        content:
          "We build practical, polished software for organizations that want technology to reduce friction rather than create it.",
        section: "story",
      },
      {
        $id: "about-vision",
        title: "Vision",
        content: "To help businesses operate with better systems, sharper visibility, and stronger digital experiences.",
        section: "vision",
      },
      {
        $id: "about-mission",
        title: "Mission",
        content: "Deliver reliable software platforms that are beautiful for customers and manageable for internal teams.",
        section: "mission",
      },
    ],
  },
  services: {
    eyebrow: "Services",
    title: "Services that cover your complete digital operation",
    subtitle: "Websites, custom applications, automation, AI integration, CMS systems, and ongoing product support.",
    collectionId: COLLECTIONS.SERVICES,
    searchFields: ["name", "category", "shortDescription"],
    primaryField: "name",
    descriptionField: "shortDescription",
    imageField: "imageMediaId",
    categoryField: "category",
    fallback: [
      { $id: "service-web", name: "Enterprise Website Development", shortDescription: "Fast, responsive, CMS-ready company websites.", category: "Web" },
      { $id: "service-app", name: "Business Web Applications", shortDescription: "Secure dashboards, portals, CRMs, and operational tools.", category: "Apps" },
      { $id: "service-ai", name: "AI & Automation", shortDescription: "Automated workflows and AI-assisted business processes.", category: "Automation" },
    ],
  },
  solutions: {
    eyebrow: "Solutions",
    title: "Digital solutions shaped around business workflows",
    subtitle: "Launch customer portals, lead systems, admin dashboards, analytics workspaces, and internal management tools.",
    collectionId: COLLECTIONS.SOLUTIONS,
    searchFields: ["name", "description", "category"],
    primaryField: "name",
    descriptionField: "description",
    imageField: "imageMediaId",
    categoryField: "category",
    fallback: [
      { $id: "solution-cms", name: "Content Management", description: "Control every visible content section through Appwrite-backed admin modules.", category: "CMS" },
      { $id: "solution-leads", name: "Lead Management", description: "Capture, review, reply, export, and track customer enquiries.", category: "Growth" },
      { $id: "solution-careers", name: "Career Operations", description: "Publish jobs and manage applications from one portal.", category: "HR" },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: "Selected work across websites, dashboards, and applications",
    subtitle: "Explore the kinds of digital products and business systems your team can manage through the platform.",
    collectionId: COLLECTIONS.PORTFOLIO,
    searchFields: ["title", "category", "description"],
    primaryField: "title",
    descriptionField: "description",
    imageField: "coverImageId",
    categoryField: "category",
    variant: "portfolio",
    fallback: [
      { $id: "portfolio-enterprise", title: "Enterprise CMS Platform", description: "A complete Appwrite-backed admin and website content system.", category: "CMS" },
      { $id: "portfolio-dashboard", title: "Operations Dashboard", description: "Metrics, contacts, jobs, applications, and reports in one workspace.", category: "Dashboard" },
      { $id: "portfolio-commerce", title: "Product Management Portal", description: "Product content, pricing, downloads, and inventory management.", category: "Commerce" },
    ],
  },
  technologies: {
    eyebrow: "Technologies",
    title: "Modern tools selected for speed, safety, and maintainability",
    subtitle: "React, TypeScript, TailwindCSS, Appwrite, TanStack Query, Zod, and practical integrations.",
    collectionId: COLLECTIONS.TECHNOLOGIES,
    searchFields: ["name", "category", "description"],
    primaryField: "name",
    descriptionField: "description",
    categoryField: "category",
    fallback: [
      { $id: "tech-react", name: "React", description: "Component-driven interfaces for public sites and admin portals.", category: "Frontend" },
      { $id: "tech-appwrite", name: "Appwrite", description: "Authentication, database, storage, and backend services.", category: "Backend" },
      { $id: "tech-typescript", name: "TypeScript", description: "Strict, scalable application code with safer refactoring.", category: "Language" },
    ],
  },
  industries: {
    eyebrow: "Industries",
    title: "Flexible software for service, product, and operations-led companies",
    subtitle: "The platform adapts to content-heavy websites, business portals, internal teams, and customer-facing workflows.",
    collectionId: COLLECTIONS.INDUSTRIES,
    searchFields: ["name", "description"],
    primaryField: "name",
    descriptionField: "description",
    fallback: [
      { $id: "industry-services", name: "Professional Services", description: "Content, enquiries, appointment booking, and case studies." },
      { $id: "industry-retail", name: "Products & Retail", description: "Catalogs, product details, media, downloads, and inventory." },
      { $id: "industry-hr", name: "Hiring Teams", description: "Job publishing, applications, resume uploads, and status workflows." },
    ],
  },
  testimonials: {
    eyebrow: "Testimonials",
    title: "Built for teams that value clear execution",
    subtitle: "Customer feedback, ratings, and stories managed directly from the admin portal.",
    collectionId: COLLECTIONS.TESTIMONIALS,
    searchFields: ["clientName", "clientCompany", "quote"],
    primaryField: "clientName",
    descriptionField: "quote",
    imageField: "avatarMediaId",
    variant: "testimonials",
    fallback: [
      { $id: "testimonial-1", clientName: "Operations Lead", clientCompany: "Growing Enterprise", quote: "The platform gave our team control over content and enquiries without waiting on code changes.", rating: 5 },
      { $id: "testimonial-2", clientName: "Founder", clientCompany: "Digital Business", quote: "The admin experience feels clean, practical, and ready for daily use.", rating: 5 },
      { $id: "testimonial-3", clientName: "HR Manager", clientCompany: "Service Company", quote: "Careers and applications are much easier to manage in one place.", rating: 5 },
    ],
  },
  careers: {
    eyebrow: "Careers",
    title: "Join a team building practical software for ambitious companies",
    subtitle: "Explore open roles and help create reliable digital systems.",
    collectionId: COLLECTIONS.JOBS,
    searchFields: ["title", "department", "location"],
    primaryField: "title",
    descriptionField: "description",
    categoryField: "department",
    variant: "careers",
    fallback: [
      { $id: "career-frontend", title: "Frontend Engineer", description: "Build polished React interfaces for public sites and admin portals.", employmentType: "full-time", location: "Remote" },
      { $id: "career-fullstack", title: "Full Stack Engineer", description: "Work across React, Appwrite, APIs, and product workflows.", employmentType: "full-time", location: "Hybrid" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Answers before we start",
    subtitle: "Common questions about websites, admin portals, content management, and project delivery.",
    collectionId: COLLECTIONS.FAQS,
    searchFields: ["question", "answer", "category"],
    primaryField: "question",
    descriptionField: "answer",
    categoryField: "category",
    fallback: [
      { $id: "faq-cms", question: "Can we edit website content ourselves?", answer: "Yes. The admin portal is designed so content, media, menus, settings, and enquiries can be managed without source-code edits.", category: "CMS" },
      { $id: "faq-storage", question: "Where are images and files stored?", answer: "Media uploads are stored in Appwrite Storage and referenced from database documents.", category: "Media" },
      { $id: "faq-auth", question: "Is the admin portal protected?", answer: "Admin routes are protected by Appwrite Authentication and the configured admin identity allowlist.", category: "Security" },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Tell us what you want to build",
    subtitle: "Share your goals, timeline, and requirements. We will help shape the right technical path.",
    collectionId: COLLECTIONS.CONTACT_REQUESTS,
    searchFields: ["name", "email", "subject"],
    primaryField: "name",
    descriptionField: "message",
    ctaLabel: "Get a quote",
    ctaPath: ROUTES.QUOTE,
    variant: "contact",
    fallback: [{ $id: "contact", name: "Contact DAN Enterprise", message: "We are ready to discuss your next website, app, or automation system." }],
  },
  privacy: {
    eyebrow: "Privacy",
    title: "Privacy Policy",
    subtitle: "How your data is handled when you use the website and admin-backed services.",
    collectionId: COLLECTIONS.POLICIES,
    searchFields: ["title", "content", "type"],
    primaryField: "title",
    descriptionField: "content",
    variant: "legal",
    fallback: [{ $id: "privacy", title: "Privacy Policy", content: "We collect only the information needed to respond to enquiries, manage services, and operate the website responsibly." }],
  },
  terms: {
    eyebrow: "Terms",
    title: "Terms & Conditions",
    subtitle: "The terms that guide use of the website and services.",
    collectionId: COLLECTIONS.POLICIES,
    searchFields: ["title", "content", "type"],
    primaryField: "title",
    descriptionField: "content",
    variant: "legal",
    fallback: [{ $id: "terms", title: "Terms & Conditions", content: "By using this website, you agree to use it responsibly and contact us for project-specific commercial terms." }],
  },
} satisfies Record<string, PublicPageConfig>;
